title: '【筆記中】【NAGOYA TEENS AI CAMP 2025】AI と一緒に宝探しの冒険へ！'

summary: '2025年の名古屋AIユースキャンプで使用する教材です。AIロボットに指示を出して、3Dマップの中で宝探しをするゲームを作ります。'

topics: ['ai', 'chatgpt', 'javascript', 'three.js', 'programming']

published: true

price: 0

chapters:
    - 01.intro
    - 02.get-started
    - 03.make-3d-game
    - 04.create-map-and-robot
    - 05.secret-and-api
    - 06.what-is-ai
    - 07.talk-to-ai-robot
    - 08.smarter-instructions
    - 09.debug
    - 10.create-original-map
    - 11.cline-setup
    - 12.cline-original-map
    - 13.summary
