title: '【筆記中】【NAGOYA TEENS AI CAMP 2025】AI と一緒に宝探しの冒険へ！'

summary: '2025年の名古屋AIユースキャンプで使用する教材です。AIロボットに指示を出して、3Dマップの中で宝探しをするゲームを作ります。'

topics: ['ai', 'chatgpt', 'javascript', 'three.js', 'programming']

published: true

price: 0

chapters:
    - 01_intro
    - 02_get_started
    - 03_make_3d_game
    - 04_create_map_and_robot
    - 05_secret_and_api
    - 06_what_is_ai
    - 07_talk_to_ai_robot
    - 08_smarter_instructions
    - 09_debug
    - 10_challenge_map2
    - 11_create_original_map
    - 12_cline_introduction
    - 13_advanced_map_creation
    - 14_advanced_challenges
    - 15_summary
