title: '【NAGOYA TEENS AI CAMP 2025】AI と一緒に宝探しの冒険へ！'

summary: '2025年の名古屋AIユースキャンプで使用する教材です。AIロボットに指示を出して、3Dマップの中で宝探しをするゲームを作ります。'

topics: ['ai', 'chatgpt', 'javascript', 'threejs', 'programming']

published: true

price: 0

chapters:
  - 00_intro
  - 01_common-environment-setup
  - 02_common-base-setup
  - 03_1st-game-setup
  - 04_1st-game-map-and-robot-setup
  - 05_1st-game-chatgpt-api
  - 06_1st-game-overview
  - 07_1st-game-tutorial
  - 08_1st-game
  - 09_2nd-game-setup
  - 10_2nd-game
  - 10_tips-what-is-ai
  - 11_3nd-game-setup
  - 11_3nd-game
  - 12_tips-ai-trivia
  - 13_advanced-create-original-map
  - 14_advanced-cline-setup
  - 15_advanced-cline-original-map
  - 16_outro
