title: '【NAGOYA TEENS AI CAMP 2025】AI と一緒に宝探しの冒険へ！'

summary: '2025年の名古屋AIユースキャンプで使用する教材です。AIロボットに指示を出して、3Dマップの中で宝探しをするゲームを作ります。'

topics: ['ai', 'chatgpt', 'javascript', 'threejs', 'programming']

published: true

price: 0

chapters:
  - 00_intro
  - 01_common-environment-setup
  - 02_common-base-setup
  - 03_common-core-setup
  - 04_common-system-prompt
  - 05_1st-game-setup
  - 06_1st-game-chatgpt-api
  - 07_1st-game-overview
  - 08_1st-game-tutorial
  - 09_1st-game
  - 10_2nd-game-setup
  - 11_2nd-game
  - 12_tips-what-is-ai
  - 13_3nd-game-setup
  - 14_3nd-game
  - 15_tips-ai-trivia
  - 16_advanced-create-original-map
  - 17_advanced-cline-setup
  - 18_advanced-cline-original-map
  - 19_outro
